controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
    
app_blog_home:
    path: /
    controller: App\Controller\BlogController::indexHome
    methods: GET
    options:
        expose: true

app_blog_login:
    path: /login
    controller: App\Controller\BlogController::login
    methods: GET
    options:
        expose: true

app_blog_verifiEmail:
    path: /verifi-email
    controller: App\Controller\BlogController::verifiEmail
    methods: GET
    options:
        expose: true

app_blog_confirmEmail:
    path: /confirm-email
    controller: App\Controller\BlogController::confirmEmail
    methods: GET
    options:
        expose: true

app_blog_formEntreprise:
    path: /registre-entreprise
    controller: App\Controller\BlogController::formEntreprise
    methods: GET
    options:
        expose: true

app_dashboard:
    path: /workspace/dashboard
    controller: App\Controller\DashboardController::index
    methods: GET
    options:
        expose: true

app_dashboard_hello:
    path: /workspace/dashboard/hello
    controller: App\Controller\DashboardController::hello
    methods: GET
    options:
        expose: true